### PR TITLE
genius.com support

### PR DESCRIPTION
**Pull request by andykog**

### CODE REVIEW

**Comment by erichlotto** [comment]
Hi Andy, thank you very much for your contribution.
I was looking into your code and it seems you've put an input tag in the options page where the user can insert the genius access token, is this correct? Any reason why not just leave the key in api_keys.js? (you can put a dummy key there and I insert a real one when publishing) I'm afraid it isn't very user-friendly having to manually insert the token after the install.
Also I'll have to change the priority in _priority.json as the timed lyrics relies entirely in vagalume api.
These are minor changes, and I appreciate if you could look into them. I can look into them sometime this weekend otherwise.

Again, thank you for helping out :)

**Comment by andykog** [comment]
@erichlotto, no problem :-) 

I haven't thought about the timed lytics, will change the priority.

bq. Any reason why not just leave the key in api_keys.js? (you can put a dummy key there and I insert a real one when publishing) 

Not sure about the limitations Genius applies to it's users. They [don't answer](https://genius.com/discussions/257837-Are-there-get-limits-can-i-use-api-for-data-mining) directly, but I can imagine they'll want to disable a token being used for hundreds of thousands searches per day. But if you think it should work I'll remove that section from the preferences.

BTW, what's the point of inserting “real one when publishing” if anybody can still easily see it with chrome devtools.

**Comment by erichlotto** [comment]
BTW, what's the point of inserting “real one when publishing” if anybody
can still easily see it with chrome devtools.
I've been thinking about this actually. I think I'll just leave the keys
publicly in the repo. They are totally free, there's no reason for someone
else to use them and would make compiling the extension extremely easier
for new contributors. What do you think?

2017-09-05 13:32 GMT-03:00 Andy Kogut <notifications@github.com>:

**Comment by andykog** [comment]
@erichlotto, I agree

**Comment by andykog** [comment]
@erichlotto, sorry for a little delay, done :-)

**Comment by erichlotto** [comment]
Sorry for the delay. Your commit is merged and being published on chrome webstore. Thanks for helping out!

**Comment by erichlotto** [comment]
Unfortunately genius is returning results other than the music requested.

For example: requesting the lyrics for Tr3s by Project46 (https://www.youtube.com/watch?v=kjqBphjxZYs) is returning this unrelated result: https://genius.com/Supreme-court-of-utah-madsen-v-east-jordan-irrigation-co-annotated

I'm afraid I'm gonna have to disable the genius integration again for now :-(

**Comment by andykog** [comment]
@erichlotto, are there any reasons not to just assign it the lowest priotity? Genius often finds lyrics while other sources used by play-music-lyrics-fetcher fail (can show you some examples if needed).
Of cource, there is a pretty straitforward workaraund for the problem — to compare artist name & song title with metadata, returned by genius api.

**Comment by erichlotto** [comment]
Simply assigning the lowest priority would still show an unrelated result if no other source succeeds. That is bad for the general user experience.
I've followed your suggestion to compare the artist/track returned and seems to have solved the issue. Will test a bit and publish the fix afterwards.

**Pull request merged**
